/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StudentId = IDL.Nat;
export const FeeCategoryId = IDL.Nat;
export const Frequency = IDL.Variant({
  'annual' : IDL.Null,
  'monthly' : IDL.Null,
  'termly' : IDL.Null,
});
export const FeeCategory = IDL.Record({
  'name' : IDL.Text,
  'frequency' : Frequency,
  'amount' : IDL.Nat,
});
export const Time = IDL.Int;
export const Student = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'grade' : IDL.Text,
  'enrollmentDate' : Time,
  'phone' : IDL.Text,
  'parentName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FeeAssignment = IDL.Record({
  'studentId' : StudentId,
  'academicYear' : IDL.Text,
  'feeCategoryId' : FeeCategoryId,
});
export const Payment = IDL.Record({
  'paymentMethod' : IDL.Text,
  'studentId' : StudentId,
  'referenceNumber' : IDL.Text,
  'date' : Time,
  'feeCategoryId' : FeeCategoryId,
  'notes' : IDL.Text,
  'amount' : IDL.Nat,
});
export const PaymentId = IDL.Nat;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignFee' : IDL.Func([StudentId, FeeCategoryId, IDL.Text], [IDL.Nat], []),
  'createFeeCategory' : IDL.Func([FeeCategory], [FeeCategoryId], []),
  'getAllFeeCategories' : IDL.Func([], [IDL.Vec(FeeCategory)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeeAssignmentsByStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(FeeAssignment)],
      ['query'],
    ),
  'getFeeCategory' : IDL.Func([FeeCategoryId], [FeeCategory], ['query']),
  'getPaymentsByStudent' : IDL.Func([StudentId], [IDL.Vec(Payment)], ['query']),
  'getStudent' : IDL.Func([StudentId], [Student], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPayment' : IDL.Func([Payment], [PaymentId], []),
  'registerStudent' : IDL.Func([Student], [StudentId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StudentId = IDL.Nat;
  const FeeCategoryId = IDL.Nat;
  const Frequency = IDL.Variant({
    'annual' : IDL.Null,
    'monthly' : IDL.Null,
    'termly' : IDL.Null,
  });
  const FeeCategory = IDL.Record({
    'name' : IDL.Text,
    'frequency' : Frequency,
    'amount' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Student = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'grade' : IDL.Text,
    'enrollmentDate' : Time,
    'phone' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FeeAssignment = IDL.Record({
    'studentId' : StudentId,
    'academicYear' : IDL.Text,
    'feeCategoryId' : FeeCategoryId,
  });
  const Payment = IDL.Record({
    'paymentMethod' : IDL.Text,
    'studentId' : StudentId,
    'referenceNumber' : IDL.Text,
    'date' : Time,
    'feeCategoryId' : FeeCategoryId,
    'notes' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const PaymentId = IDL.Nat;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignFee' : IDL.Func([StudentId, FeeCategoryId, IDL.Text], [IDL.Nat], []),
    'createFeeCategory' : IDL.Func([FeeCategory], [FeeCategoryId], []),
    'getAllFeeCategories' : IDL.Func([], [IDL.Vec(FeeCategory)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeeAssignmentsByStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(FeeAssignment)],
        ['query'],
      ),
    'getFeeCategory' : IDL.Func([FeeCategoryId], [FeeCategory], ['query']),
    'getPaymentsByStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getStudent' : IDL.Func([StudentId], [Student], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPayment' : IDL.Func([Payment], [PaymentId], []),
    'registerStudent' : IDL.Func([Student], [StudentId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };