/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FeeAssignment {
  'studentId' : StudentId,
  'academicYear' : string,
  'feeCategoryId' : FeeCategoryId,
}
export interface FeeCategory {
  'name' : string,
  'frequency' : Frequency,
  'amount' : bigint,
}
export type FeeCategoryId = bigint;
export type Frequency = { 'annual' : null } |
  { 'monthly' : null } |
  { 'termly' : null };
export interface Payment {
  'paymentMethod' : string,
  'studentId' : StudentId,
  'referenceNumber' : string,
  'date' : Time,
  'feeCategoryId' : FeeCategoryId,
  'notes' : string,
  'amount' : bigint,
}
export type PaymentId = bigint;
export interface Student {
  'name' : string,
  'email' : string,
  'grade' : string,
  'enrollmentDate' : Time,
  'phone' : string,
  'parentName' : string,
}
export type StudentId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignFee' : ActorMethod<[StudentId, FeeCategoryId, string], bigint>,
  'createFeeCategory' : ActorMethod<[FeeCategory], FeeCategoryId>,
  'getAllFeeCategories' : ActorMethod<[], Array<FeeCategory>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeeAssignmentsByStudent' : ActorMethod<[StudentId], Array<FeeAssignment>>,
  'getFeeCategory' : ActorMethod<[FeeCategoryId], FeeCategory>,
  'getPaymentsByStudent' : ActorMethod<[StudentId], Array<Payment>>,
  'getStudent' : ActorMethod<[StudentId], Student>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordPayment' : ActorMethod<[Payment], PaymentId>,
  'registerStudent' : ActorMethod<[Student], StudentId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];